# Generated by Django 3.2.9 on 2021-12-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('total_count', models.IntegerField()),
            ],
        ),
    ]
