# Generated by Django 3.2.9 on 2021-12-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars_explorer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
