# Generated by Django 3.2.9 on 2021-12-07 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starwars_explorer', '0002_fetchstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FetchStatus',
        ),
    ]
